### ISSUE TITLE
PhishingTemplate' object has no attribute 'get_display_name

### ISSUE THREAD

**Issue by JBelinchon** [wifiphisher/wifiphisher#999]
**Version**: Use `git show | grep commit` command and paste here the output.

commit fd85121929cd73d5208bb51bd61d4d088cee1d9d

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

OS: Kali Linux 2018.3
```
root@kali:~/Downloads/wifiphisher# iwconfig 
wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=0 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:on
```

**Script output**: Paste the output of the tool, including any stack traces.
When I run `wifiphisher --noextensions --essid "FREE WI-FI" -p oauth-login -kB` I always get this error:
```
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 655, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 501, in start
    template.get_display_name() + " template")
AttributeError: 'PhishingTemplate' object has no attribute 'get_display_name'
```

**Comment by sophron** [comment]
This bug was introduced after merging #975.

I can fix it later today.

**Comment by JBelinchon** [comment]
Hi, guys, 
After a git pull I now get a different error:

![captura](https://user-images.githubusercontent.com/28694510/44997971-50d55d80-afb2-11e8-9c2c-ea96cd7ace9a.png)

`Traceback (most recent call last):
  File "/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 655, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 501, in start
    template.get_display_name() + " template")
AttributeError: 'PhishingTemplate' object has no attribute 'get_display_name'
`

**Comment by sophron** [comment]
You haven't applied the pulled changes. You need to do `python bin/wifiphisher` or `python setup.py install` (and then `wifiphisher`) to see them in action.

**Comment by JBelinchon** [comment]
I have updated my previous comment.. Please check it out.

Regards

**Comment by JBelinchon** [comment]
Sorry, what I mean is that after the last fix: https://github.com/wifiphisher/wifiphisher/commit/27c28d9c7ebd916ff370b16092cb46482726aafa I get a different error:

`Traceback (most recent call last): File "bin/wifiphisher", line 17, in <module> run() File "/root/Downloads/wifiphisher/wifiphisher/pywifiphisher.py", line 655, in run engine.start() File "/root/Downloads/wifiphisher/wifiphisher/pywifiphisher.py", line 532, in start template.merge_context({'APs': APs_context}) File "/root/Downloads/wifiphisher/wifiphisher/common/phishingpage.py", line 103, in merge_context context.update(self._context) AttributeError: 'PhishingTemplate' object has no attribute '_context''`

**Comment by blackHatMonkey** [comment]
@sophron Did you force push master?

**Comment by JBelinchon** [comment]
I had to install manually some missing lib-dev packages (apt-get install libnl-3-dev libnl-genl-3-dev libssl-dev ) and after that I had to manually install roguehostapd. 

After that everyting is working great.

Thanks a lot Gerge !!
